statefulset:
  enabled: true
replicaCount: 1
nexus:
  imageName: 308882746353.dkr.ecr.us-east-1.amazonaws.com/parkassist/sonatype-nexus
  resources:
    requests:
      cpu: 250m
      memory: 4800Mi
nexusProxy:
  enabled: false
persistence:
  storageClass: gp2
  pdName: nexus-data-disk
  fsType: ext4
ingress:
  tls:
    enabled: false
serviceAccount:
  create: false
service:
  enabled: true
  name: sonatype-nexus-lb
  type: LoadBalancer
  labels:
    app: "sonatype-nexus"
    dns: "route53"
  annotations:
    domainName: "nexus.parkassist.com"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:308882746353:certificate/37eea134-8fa3-49ea-b24b-7da0b3d34abf"
  ports:
  - name: https
    targetPort: 8081
    port: 443